version: '3.8'

services:
  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=timecopsync_crud_test
    ports:
      - '5432:5432'
